services:
  web:
    image: daily-quote
    # container_name: 
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    command: php artisan serve --host 0.0.0.0 --port 8080
    volumes:
      - ./myapp:/src
    ports:
      - "8080:8080"
    restart: always
