services:
  web:
    image: daily-quote
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    command: command/serve.sh local
    # volumes:
    #   - ./src:/myapp
    ports:
      - "8080:8080"
    restart: always
